// <auto-generated />
using System;
using LabAWC_RiusLaura.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Restaurante_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241205144519_migracionFinal")]
    partial class migracionFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.ToTable("Comandas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MesaId = 1,
                            NombreCliente = "Cliente A"
                        },
                        new
                        {
                            Id = 2,
                            MesaId = 2,
                            NombreCliente = "Cliente B"
                        },
                        new
                        {
                            Id = 3,
                            MesaId = 3,
                            NombreCliente = "Cliente C"
                        },
                        new
                        {
                            Id = 4,
                            MesaId = 4,
                            NombreCliente = "Cliente D"
                        },
                        new
                        {
                            Id = 5,
                            MesaId = 1,
                            NombreCliente = "Cliente E"
                        });
                });

            modelBuilder.Entity("Entidades.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EmpleadoActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("SectorId");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpleadoActivo = true,
                            Nombre = "Juan Pérez",
                            Password = "bartender1",
                            RolId = 1,
                            SectorId = 1,
                            Usuario = "bartender1"
                        },
                        new
                        {
                            Id = 2,
                            EmpleadoActivo = true,
                            Nombre = "María Gómez",
                            Password = "cervecero1",
                            RolId = 2,
                            SectorId = 2,
                            Usuario = "cervecero1"
                        },
                        new
                        {
                            Id = 3,
                            EmpleadoActivo = true,
                            Nombre = "Carlos López",
                            Password = "cocinero1",
                            RolId = 3,
                            SectorId = 3,
                            Usuario = "cocinero1"
                        },
                        new
                        {
                            Id = 4,
                            EmpleadoActivo = true,
                            Nombre = "Ana Martínez",
                            Password = "mozo1",
                            RolId = 4,
                            SectorId = 4,
                            Usuario = "mozo1"
                        },
                        new
                        {
                            Id = 5,
                            EmpleadoActivo = true,
                            Nombre = "Jorge García",
                            Password = "socio1",
                            RolId = 5,
                            SectorId = 5,
                            Usuario = "socio1"
                        },
                        new
                        {
                            Id = 6,
                            EmpleadoActivo = false,
                            Nombre = "Laura Torres",
                            Password = "bartender2",
                            RolId = 1,
                            SectorId = 1,
                            Usuario = "bartender2"
                        },
                        new
                        {
                            Id = 7,
                            EmpleadoActivo = true,
                            Nombre = "Esteban Rodriguez",
                            Password = "socio2",
                            RolId = 5,
                            SectorId = 5,
                            Usuario = "socio2"
                        },
                        new
                        {
                            Id = 8,
                            EmpleadoActivo = true,
                            Nombre = "Pedro Ramirez",
                            Password = "cocinero2",
                            RolId = 3,
                            SectorId = 3,
                            Usuario = "cocinero2"
                        },
                        new
                        {
                            Id = 9,
                            EmpleadoActivo = false,
                            Nombre = "Gonzalo Fernandez",
                            Password = "socio3",
                            RolId = 5,
                            SectorId = 5,
                            Usuario = "socio3"
                        });
                });

            modelBuilder.Entity("Entidades.EstadoMesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados_Mesas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Cliente Esperando Pedido"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cliente Comiendo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cliente Pagando"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Cerrada"
                        });
                });

            modelBuilder.Entity("Entidades.EstadoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados_Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "En Preparacion"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Listo Para Servir"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Servido"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Cancelado"
                        });
                });

            modelBuilder.Entity("Entidades.LogueoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoLogId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDeslogueo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLogueo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoLogId");

                    b.ToTable("LogueosEmpleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpleadoLogId = 1,
                            FechaDeslogueo = new DateTime(2024, 8, 12, 23, 59, 0, 0, DateTimeKind.Local),
                            FechaLogueo = new DateTime(2024, 8, 12, 19, 6, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            EmpleadoLogId = 2,
                            FechaDeslogueo = new DateTime(2024, 8, 12, 23, 59, 0, 0, DateTimeKind.Local),
                            FechaLogueo = new DateTime(2024, 8, 12, 19, 1, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            EmpleadoLogId = 3,
                            FechaDeslogueo = new DateTime(2024, 8, 12, 23, 49, 0, 0, DateTimeKind.Local),
                            FechaLogueo = new DateTime(2024, 8, 12, 17, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            EmpleadoLogId = 4,
                            FechaDeslogueo = new DateTime(2024, 8, 12, 23, 15, 0, 0, DateTimeKind.Local),
                            FechaLogueo = new DateTime(2024, 8, 12, 18, 16, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            EmpleadoLogId = 5,
                            FechaDeslogueo = new DateTime(2024, 8, 13, 23, 33, 0, 0, DateTimeKind.Local),
                            FechaLogueo = new DateTime(2024, 8, 13, 19, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            EmpleadoLogId = 6,
                            FechaDeslogueo = new DateTime(2024, 8, 13, 23, 55, 0, 0, DateTimeKind.Local),
                            FechaLogueo = new DateTime(2024, 8, 13, 19, 30, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Entidades.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("EstadoMesaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoMesaId");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "URVTG",
                            EstadoMesaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "40MMY",
                            EstadoMesaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "8O330",
                            EstadoMesaId = 4
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "EKI9D",
                            EstadoMesaId = 1
                        });
                });

            modelBuilder.Entity("Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("ComandaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPedidoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("TiempoEstimado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("EstadoPedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            CodigoCliente = "6XT3S",
                            ComandaId = 1,
                            EstadoPedidoId = 1,
                            FechaCreacion = new DateTime(2024, 8, 12, 19, 30, 0, 0, DateTimeKind.Local),
                            Observaciones = "Con hielo",
                            ProductoId = 1,
                            TiempoEstimado = 10
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 2,
                            CodigoCliente = "CD1JM",
                            ComandaId = 1,
                            EstadoPedidoId = 1,
                            FechaCreacion = new DateTime(2024, 8, 12, 19, 30, 0, 0, DateTimeKind.Local),
                            Observaciones = "",
                            ProductoId = 3,
                            TiempoEstimado = 20
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 3,
                            CodigoCliente = "3WANA",
                            ComandaId = 1,
                            EstadoPedidoId = 1,
                            FechaCreacion = new DateTime(2024, 8, 12, 19, 30, 0, 0, DateTimeKind.Local),
                            Observaciones = "",
                            ProductoId = 3,
                            TiempoEstimado = 30
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 2,
                            CodigoCliente = "P91CI",
                            ComandaId = 2,
                            EstadoPedidoId = 1,
                            FechaCreacion = new DateTime(2024, 8, 12, 19, 30, 0, 0, DateTimeKind.Local),
                            Observaciones = "",
                            ProductoId = 8,
                            TiempoEstimado = 15
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 2,
                            CodigoCliente = "G5OHV",
                            ComandaId = 3,
                            EstadoPedidoId = 1,
                            FechaCreacion = new DateTime(2024, 8, 12, 19, 30, 0, 0, DateTimeKind.Local),
                            Observaciones = "",
                            ProductoId = 9,
                            TiempoEstimado = 40
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 4,
                            CodigoCliente = "R2TTZ",
                            ComandaId = 5,
                            EstadoPedidoId = 4,
                            FechaCreacion = new DateTime(2024, 8, 24, 19, 30, 0, 0, DateTimeKind.Local),
                            FechaFinalizacion = new DateTime(2024, 8, 24, 19, 47, 0, 0, DateTimeKind.Local),
                            Observaciones = "bien frío",
                            ProductoId = 2,
                            TiempoEstimado = 15
                        });
                });

            modelBuilder.Entity("Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreDesc = "Vino tinto Malbec",
                            Precio = 14000.00m,
                            SectorId = 1,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            NombreDesc = "Vino tinto Cabernet",
                            Precio = 14000.00m,
                            SectorId = 1,
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            NombreDesc = "Cerveza artesanal IPA Roja",
                            Precio = 3700.00m,
                            SectorId = 2,
                            Stock = 200
                        },
                        new
                        {
                            Id = 4,
                            NombreDesc = "Cerveza artesanal Negra",
                            Precio = 3700.00m,
                            SectorId = 2,
                            Stock = 150
                        },
                        new
                        {
                            Id = 5,
                            NombreDesc = "Empanadas de Carne",
                            Precio = 1500.00m,
                            SectorId = 3,
                            Stock = 200
                        },
                        new
                        {
                            Id = 6,
                            NombreDesc = "Empanadas de Verdura",
                            Precio = 1500.00m,
                            SectorId = 3,
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            NombreDesc = "Empanadas de Pollo",
                            Precio = 1500.00m,
                            SectorId = 3,
                            Stock = 150
                        },
                        new
                        {
                            Id = 8,
                            NombreDesc = "Postre Tiramisú",
                            Precio = 5000.00m,
                            SectorId = 4,
                            Stock = 40
                        },
                        new
                        {
                            Id = 9,
                            NombreDesc = "Café",
                            Precio = 2500.00m,
                            SectorId = 4,
                            Stock = 400
                        });
                });

            modelBuilder.Entity("Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Bartender"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cervecero"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cocinero"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Mozo"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Socio"
                        });
                });

            modelBuilder.Entity("Entidades.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sectores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Barra Tragos Y Vino"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cerveza Artesanal"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cocina"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Candybar"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "General"
                        });
                });

            modelBuilder.Entity("Entidades.Comanda", b =>
                {
                    b.HasOne("Entidades.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("Entidades.Empleado", b =>
                {
                    b.HasOne("Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Entidades.LogueoEmpleado", b =>
                {
                    b.HasOne("Entidades.Empleado", "EmpleadoLog")
                        .WithMany()
                        .HasForeignKey("EmpleadoLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpleadoLog");
                });

            modelBuilder.Entity("Entidades.Mesa", b =>
                {
                    b.HasOne("Entidades.EstadoMesa", "EstadoMesa")
                        .WithMany()
                        .HasForeignKey("EstadoMesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoMesa");
                });

            modelBuilder.Entity("Entidades.Pedido", b =>
                {
                    b.HasOne("Entidades.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.EstadoPedido", "EstadoPedido")
                        .WithMany()
                        .HasForeignKey("EstadoPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("EstadoPedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Entidades.Producto", b =>
                {
                    b.HasOne("Entidades.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });
#pragma warning restore 612, 618
        }
    }
}
